### ISSUE TITLE
Fix some typos in README

### ISSUE THREAD

**Issue by csarnataro** [fastify/fastify-hotwire#1]
## 🐛 Bug Report

This is not really a bug, it's more a minor update to documentation (but I couldn't find a specific template for docs).
I noticed a couple of typos in the README file, and since this example with hotwire is very helpful, I think it would be useful for readers to have a more accurate documentation. 

## To Reproduce

N/A

## Expected behavior

The documentation should not contains typos. I'm opening a PR soon.

## Your Environment

N/A

**Comment by climba03003** [comment]
Resolved by #2 
@mcollina Can you kindly help to close this issue? I do not have permission on this repo.
